### ISSUE TITLE
Conference variable

### ISSUE THREAD

**Issue by drewflaherty95** [dsi-principles-prog/midterm-drewflaherty95#2]
Problem: The level of play is different between the Western and Eastern Conferences. I believe that the strength of teams in one conference could potentially impact the number of points scored by a player. I want to create a variable that gives a numeric representation for each conference. This will be useful when inputting it into a machine learning algorithm. 

Input: Column variable for conference. Labelled "con" in the data set

Output: a value of 1 for the Western Conference and 0 for the Eastern Conference

**Comment by umangchaudhry** [comment]
Added feature conference to output a 0 or a 1 based on whether the team is in the western or eastern conference. Added assert to test the feature in notebook 40-modelling. This closes the issue.
